export const mockData = [
  {
    __typename: "OperatorObservation",
    value: 14.546839081431266,
    municipalityLabel: "Municipality 1",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 1, Operator 1",
    municipality: "muni-1",
    operator: "op-1",
    canton: "canton-1",
    cantonLabel: "Canton 1",
  },
  {
    __typename: "OperatorObservation",
    value: 22.67663102741797,
    municipalityLabel: "Municipality 2",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 2, Operator 1",
    municipality: "muni-2",
    operator: "op-1",
    canton: "canton-2",
    cantonLabel: "Canton 2",
  },
  {
    __typename: "OperatorObservation",
    value: 26.022873041587612,
    municipalityLabel: "Municipality 3",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 3, Operator 1",
    municipality: "muni-3",
    operator: "op-1",
    canton: "canton-3",
    cantonLabel: "Canton 3",
  },
  {
    __typename: "OperatorObservation",
    value: 9.374385406413019,
    municipalityLabel: "Municipality 4",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 4, Operator 1",
    municipality: "muni-4",
    operator: "op-1",
    canton: "canton-4",
    cantonLabel: "Canton 4",
  },
  {
    __typename: "OperatorObservation",
    value: 22.75910297524843,
    municipalityLabel: "Municipality 5",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 5, Operator 1",
    municipality: "muni-5",
    operator: "op-1",
    canton: "canton-5",
    cantonLabel: "Canton 5",
  },
  {
    __typename: "OperatorObservation",
    value: 21.621097977914232,
    municipalityLabel: "Municipality 6",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 6, Operator 1",
    municipality: "muni-6",
    operator: "op-1",
    canton: "canton-6",
    cantonLabel: "Canton 6",
  },
  {
    __typename: "OperatorObservation",
    value: 25.233510363565152,
    municipalityLabel: "Municipality 7",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 7, Operator 1",
    municipality: "muni-7",
    operator: "op-1",
    canton: "canton-7",
    cantonLabel: "Canton 7",
  },
  {
    __typename: "OperatorObservation",
    value: 19.147834610040732,
    municipalityLabel: "Municipality 8",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 8, Operator 1",
    municipality: "muni-8",
    operator: "op-1",
    canton: "canton-8",
    cantonLabel: "Canton 8",
  },
  {
    __typename: "OperatorObservation",
    value: 24.225976905605663,
    municipalityLabel: "Municipality 9",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 9, Operator 1",
    municipality: "muni-9",
    operator: "op-1",
    canton: "canton-9",
    cantonLabel: "Canton 9",
  },
  {
    __typename: "OperatorObservation",
    value: 23.30421860926552,
    municipalityLabel: "Municipality 10",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 10, Operator 1",
    municipality: "muni-10",
    operator: "op-1",
    canton: "canton-10",
    cantonLabel: "Canton 10",
  },
  {
    __typename: "OperatorObservation",
    value: 19.52173649098963,
    municipalityLabel: "Municipality 11",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 11, Operator 1",
    municipality: "muni-11",
    operator: "op-1",
    canton: "canton-1",
    cantonLabel: "Canton 1",
  },
  {
    __typename: "OperatorObservation",
    value: 18.57924172186548,
    municipalityLabel: "Municipality 12",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 12, Operator 1",
    municipality: "muni-12",
    operator: "op-1",
    canton: "canton-2",
    cantonLabel: "Canton 2",
  },
  {
    __typename: "OperatorObservation",
    value: 21.980406556187432,
    municipalityLabel: "Municipality 13",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 13, Operator 1",
    municipality: "muni-13",
    operator: "op-1",
    canton: "canton-3",
    cantonLabel: "Canton 3",
  },
  {
    __typename: "OperatorObservation",
    value: 24.984636643893587,
    municipalityLabel: "Municipality 14",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 14, Operator 1",
    municipality: "muni-14",
    operator: "op-1",
    canton: "canton-4",
    cantonLabel: "Canton 4",
  },
  {
    __typename: "OperatorObservation",
    value: 19.93284124959139,
    municipalityLabel: "Municipality 15",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 15, Operator 1",
    municipality: "muni-15",
    operator: "op-1",
    canton: "canton-5",
    cantonLabel: "Canton 5",
  },
  {
    __typename: "OperatorObservation",
    value: 18.813905348034552,
    municipalityLabel: "Municipality 16",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 16, Operator 1",
    municipality: "muni-16",
    operator: "op-1",
    canton: "canton-6",
    cantonLabel: "Canton 6",
  },
  {
    __typename: "OperatorObservation",
    value: 21.78120720594222,
    municipalityLabel: "Municipality 17",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 17, Operator 1",
    municipality: "muni-17",
    operator: "op-1",
    canton: "canton-7",
    cantonLabel: "Canton 7",
  },
  {
    __typename: "OperatorObservation",
    value: 22.667079871161853,
    municipalityLabel: "Municipality 18",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 18, Operator 1",
    municipality: "muni-18",
    operator: "op-1",
    canton: "canton-8",
    cantonLabel: "Canton 8",
  },
  {
    __typename: "OperatorObservation",
    value: 18.722724249300146,
    municipalityLabel: "Municipality 19",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 19, Operator 1",
    municipality: "muni-19",
    operator: "op-1",
    canton: "canton-9",
    cantonLabel: "Canton 9",
  },
  {
    __typename: "OperatorObservation",
    value: 10.38032912610025,
    municipalityLabel: "Municipality 20",
    operatorLabel: "Operator 1",
    muniOperator: "Municipality 20, Operator 1",
    municipality: "muni-20",
    operator: "op-1",
    canton: "canton-10",
    cantonLabel: "Canton 10",
  },
  {
    __typename: "OperatorObservation",
    value: 14.76533207909604,
    municipalityLabel: "Municipality 1",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 1, Operator 2",
    municipality: "muni-1",
    operator: "op-2",
    canton: "canton-1",
    cantonLabel: "Canton 1",
  },
  {
    __typename: "OperatorObservation",
    value: 25.5792377046199,
    municipalityLabel: "Municipality 2",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 2, Operator 2",
    municipality: "muni-2",
    operator: "op-2",
    canton: "canton-2",
    cantonLabel: "Canton 2",
  },
  {
    __typename: "OperatorObservation",
    value: 25.817217167372284,
    municipalityLabel: "Municipality 3",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 3, Operator 2",
    municipality: "muni-3",
    operator: "op-2",
    canton: "canton-3",
    cantonLabel: "Canton 3",
  },
  {
    __typename: "OperatorObservation",
    value: 21.432235352552958,
    municipalityLabel: "Municipality 4",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 4, Operator 2",
    municipality: "muni-4",
    operator: "op-2",
    canton: "canton-4",
    cantonLabel: "Canton 4",
  },
  {
    __typename: "OperatorObservation",
    value: 19.60254019741169,
    municipalityLabel: "Municipality 5",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 5, Operator 2",
    municipality: "muni-5",
    operator: "op-2",
    canton: "canton-5",
    cantonLabel: "Canton 5",
  },
  {
    __typename: "OperatorObservation",
    value: 20.434654536433083,
    municipalityLabel: "Municipality 6",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 6, Operator 2",
    municipality: "muni-6",
    operator: "op-2",
    canton: "canton-6",
    cantonLabel: "Canton 6",
  },
  {
    __typename: "OperatorObservation",
    value: 28.02440197985831,
    municipalityLabel: "Municipality 7",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 7, Operator 2",
    municipality: "muni-7",
    operator: "op-2",
    canton: "canton-7",
    cantonLabel: "Canton 7",
  },
  {
    __typename: "OperatorObservation",
    value: 9.143859416880664,
    municipalityLabel: "Municipality 8",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 8, Operator 2",
    municipality: "muni-8",
    operator: "op-2",
    canton: "canton-8",
    cantonLabel: "Canton 8",
  },
  {
    __typename: "OperatorObservation",
    value: 12.434483525486968,
    municipalityLabel: "Municipality 9",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 9, Operator 2",
    municipality: "muni-9",
    operator: "op-2",
    canton: "canton-9",
    cantonLabel: "Canton 9",
  },
  {
    __typename: "OperatorObservation",
    value: 25.006300667667865,
    municipalityLabel: "Municipality 10",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 10, Operator 2",
    municipality: "muni-10",
    operator: "op-2",
    canton: "canton-10",
    cantonLabel: "Canton 10",
  },
  {
    __typename: "OperatorObservation",
    value: 22.01620042835802,
    municipalityLabel: "Municipality 11",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 11, Operator 2",
    municipality: "muni-11",
    operator: "op-2",
    canton: "canton-1",
    cantonLabel: "Canton 1",
  },
  {
    __typename: "OperatorObservation",
    value: 19.120903526567343,
    municipalityLabel: "Municipality 12",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 12, Operator 2",
    municipality: "muni-12",
    operator: "op-2",
    canton: "canton-2",
    cantonLabel: "Canton 2",
  },
  {
    __typename: "OperatorObservation",
    value: 20.963150636046855,
    municipalityLabel: "Municipality 13",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 13, Operator 2",
    municipality: "muni-13",
    operator: "op-2",
    canton: "canton-3",
    cantonLabel: "Canton 3",
  },
  {
    __typename: "OperatorObservation",
    value: 22.900503299934165,
    municipalityLabel: "Municipality 14",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 14, Operator 2",
    municipality: "muni-14",
    operator: "op-2",
    canton: "canton-4",
    cantonLabel: "Canton 4",
  },
  {
    __typename: "OperatorObservation",
    value: 18.94306232099644,
    municipalityLabel: "Municipality 15",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 15, Operator 2",
    municipality: "muni-15",
    operator: "op-2",
    canton: "canton-5",
    cantonLabel: "Canton 5",
  },
  {
    __typename: "OperatorObservation",
    value: 15.897031621587075,
    municipalityLabel: "Municipality 16",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 16, Operator 2",
    municipality: "muni-16",
    operator: "op-2",
    canton: "canton-6",
    cantonLabel: "Canton 6",
  },
  {
    __typename: "OperatorObservation",
    value: 21.498853672975525,
    municipalityLabel: "Municipality 17",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 17, Operator 2",
    municipality: "muni-17",
    operator: "op-2",
    canton: "canton-7",
    cantonLabel: "Canton 7",
  },
  {
    __typename: "OperatorObservation",
    value: 22.707167746330683,
    municipalityLabel: "Municipality 18",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 18, Operator 2",
    municipality: "muni-18",
    operator: "op-2",
    canton: "canton-8",
    cantonLabel: "Canton 8",
  },
  {
    __typename: "OperatorObservation",
    value: 17.25899844115238,
    municipalityLabel: "Municipality 19",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 19, Operator 2",
    municipality: "muni-19",
    operator: "op-2",
    canton: "canton-9",
    cantonLabel: "Canton 9",
  },
  {
    __typename: "OperatorObservation",
    value: 20.62982953709177,
    municipalityLabel: "Municipality 20",
    operatorLabel: "Operator 2",
    muniOperator: "Municipality 20, Operator 2",
    municipality: "muni-20",
    operator: "op-2",
    canton: "canton-10",
    cantonLabel: "Canton 10",
  },
  {
    __typename: "OperatorObservation",
    value: 24.00111605045347,
    municipalityLabel: "Municipality 1",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 1, Operator 3",
    municipality: "muni-1",
    operator: "op-3",
    canton: "canton-1",
    cantonLabel: "Canton 1",
  },
  {
    __typename: "OperatorObservation",
    value: 18.965587147437393,
    municipalityLabel: "Municipality 2",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 2, Operator 3",
    municipality: "muni-2",
    operator: "op-3",
    canton: "canton-2",
    cantonLabel: "Canton 2",
  },
  {
    __typename: "OperatorObservation",
    value: 22.022616465642066,
    municipalityLabel: "Municipality 3",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 3, Operator 3",
    municipality: "muni-3",
    operator: "op-3",
    canton: "canton-3",
    cantonLabel: "Canton 3",
  },
  {
    __typename: "OperatorObservation",
    value: 22.56108019090592,
    municipalityLabel: "Municipality 4",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 4, Operator 3",
    municipality: "muni-4",
    operator: "op-3",
    canton: "canton-4",
    cantonLabel: "Canton 4",
  },
  {
    __typename: "OperatorObservation",
    value: 17.5550204878021,
    municipalityLabel: "Municipality 5",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 5, Operator 3",
    municipality: "muni-5",
    operator: "op-3",
    canton: "canton-5",
    cantonLabel: "Canton 5",
  },
  {
    __typename: "OperatorObservation",
    value: 23.080866872647743,
    municipalityLabel: "Municipality 6",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 6, Operator 3",
    municipality: "muni-6",
    operator: "op-3",
    canton: "canton-6",
    cantonLabel: "Canton 6",
  },
  {
    __typename: "OperatorObservation",
    value: 20.502232823553648,
    municipalityLabel: "Municipality 7",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 7, Operator 3",
    municipality: "muni-7",
    operator: "op-3",
    canton: "canton-7",
    cantonLabel: "Canton 7",
  },
  {
    __typename: "OperatorObservation",
    value: 23.383819191455256,
    municipalityLabel: "Municipality 8",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 8, Operator 3",
    municipality: "muni-8",
    operator: "op-3",
    canton: "canton-8",
    cantonLabel: "Canton 8",
  },
  {
    __typename: "OperatorObservation",
    value: 15.257277435943468,
    municipalityLabel: "Municipality 9",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 9, Operator 3",
    municipality: "muni-9",
    operator: "op-3",
    canton: "canton-9",
    cantonLabel: "Canton 9",
  },
  {
    __typename: "OperatorObservation",
    value: 24.599886275451155,
    municipalityLabel: "Municipality 10",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 10, Operator 3",
    municipality: "muni-10",
    operator: "op-3",
    canton: "canton-10",
    cantonLabel: "Canton 10",
  },
  {
    __typename: "OperatorObservation",
    value: 15.195510865249208,
    municipalityLabel: "Municipality 11",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 11, Operator 3",
    municipality: "muni-11",
    operator: "op-3",
    canton: "canton-1",
    cantonLabel: "Canton 1",
  },
  {
    __typename: "OperatorObservation",
    value: 16.55096599502229,
    municipalityLabel: "Municipality 12",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 12, Operator 3",
    municipality: "muni-12",
    operator: "op-3",
    canton: "canton-2",
    cantonLabel: "Canton 2",
  },
  {
    __typename: "OperatorObservation",
    value: 16.938731615687267,
    municipalityLabel: "Municipality 13",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 13, Operator 3",
    municipality: "muni-13",
    operator: "op-3",
    canton: "canton-3",
    cantonLabel: "Canton 3",
  },
  {
    __typename: "OperatorObservation",
    value: 20.475291432653968,
    municipalityLabel: "Municipality 14",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 14, Operator 3",
    municipality: "muni-14",
    operator: "op-3",
    canton: "canton-4",
    cantonLabel: "Canton 4",
  },
  {
    __typename: "OperatorObservation",
    value: 14.759381314977736,
    municipalityLabel: "Municipality 15",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 15, Operator 3",
    municipality: "muni-15",
    operator: "op-3",
    canton: "canton-5",
    cantonLabel: "Canton 5",
  },
  {
    __typename: "OperatorObservation",
    value: 24.45700883352259,
    municipalityLabel: "Municipality 16",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 16, Operator 3",
    municipality: "muni-16",
    operator: "op-3",
    canton: "canton-6",
    cantonLabel: "Canton 6",
  },
  {
    __typename: "OperatorObservation",
    value: 18.081213740021955,
    municipalityLabel: "Municipality 17",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 17, Operator 3",
    municipality: "muni-17",
    operator: "op-3",
    canton: "canton-7",
    cantonLabel: "Canton 7",
  },
  {
    __typename: "OperatorObservation",
    value: 21.219846304957784,
    municipalityLabel: "Municipality 18",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 18, Operator 3",
    municipality: "muni-18",
    operator: "op-3",
    canton: "canton-8",
    cantonLabel: "Canton 8",
  },
  {
    __typename: "OperatorObservation",
    value: 23.660993831855752,
    municipalityLabel: "Municipality 19",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 19, Operator 3",
    municipality: "muni-19",
    operator: "op-3",
    canton: "canton-9",
    cantonLabel: "Canton 9",
  },
  {
    __typename: "OperatorObservation",
    value: 13.382873796251673,
    municipalityLabel: "Municipality 20",
    operatorLabel: "Operator 3",
    muniOperator: "Municipality 20, Operator 3",
    municipality: "muni-20",
    operator: "op-3",
    canton: "canton-10",
    cantonLabel: "Canton 10",
  },
  {
    __typename: "OperatorObservation",
    value: 20.074159265445598,
    municipalityLabel: "Municipality 1",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 1, Operator 4",
    municipality: "muni-1",
    operator: "op-4",
    canton: "canton-1",
    cantonLabel: "Canton 1",
  },
  {
    __typename: "OperatorObservation",
    value: 14.67516567991482,
    municipalityLabel: "Municipality 2",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 2, Operator 4",
    municipality: "muni-2",
    operator: "op-4",
    canton: "canton-2",
    cantonLabel: "Canton 2",
  },
  {
    __typename: "OperatorObservation",
    value: 13.93950787744856,
    municipalityLabel: "Municipality 3",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 3, Operator 4",
    municipality: "muni-3",
    operator: "op-4",
    canton: "canton-3",
    cantonLabel: "Canton 3",
  },
  {
    __typename: "OperatorObservation",
    value: 14.899058312340847,
    municipalityLabel: "Municipality 4",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 4, Operator 4",
    municipality: "muni-4",
    operator: "op-4",
    canton: "canton-4",
    cantonLabel: "Canton 4",
  },
  {
    __typename: "OperatorObservation",
    value: 25.184830694054405,
    municipalityLabel: "Municipality 5",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 5, Operator 4",
    municipality: "muni-5",
    operator: "op-4",
    canton: "canton-5",
    cantonLabel: "Canton 5",
  },
  {
    __typename: "OperatorObservation",
    value: 17.10834947019632,
    municipalityLabel: "Municipality 6",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 6, Operator 4",
    municipality: "muni-6",
    operator: "op-4",
    canton: "canton-6",
    cantonLabel: "Canton 6",
  },
  {
    __typename: "OperatorObservation",
    value: 18.51039661454883,
    municipalityLabel: "Municipality 7",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 7, Operator 4",
    municipality: "muni-7",
    operator: "op-4",
    canton: "canton-7",
    cantonLabel: "Canton 7",
  },
  {
    __typename: "OperatorObservation",
    value: 12.603079348097253,
    municipalityLabel: "Municipality 8",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 8, Operator 4",
    municipality: "muni-8",
    operator: "op-4",
    canton: "canton-8",
    cantonLabel: "Canton 8",
  },
  {
    __typename: "OperatorObservation",
    value: 18.76791517327771,
    municipalityLabel: "Municipality 9",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 9, Operator 4",
    municipality: "muni-9",
    operator: "op-4",
    canton: "canton-9",
    cantonLabel: "Canton 9",
  },
  {
    __typename: "OperatorObservation",
    value: 22.905444156335008,
    municipalityLabel: "Municipality 10",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 10, Operator 4",
    municipality: "muni-10",
    operator: "op-4",
    canton: "canton-10",
    cantonLabel: "Canton 10",
  },
  {
    __typename: "OperatorObservation",
    value: 21.11135661229024,
    municipalityLabel: "Municipality 11",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 11, Operator 4",
    municipality: "muni-11",
    operator: "op-4",
    canton: "canton-1",
    cantonLabel: "Canton 1",
  },
  {
    __typename: "OperatorObservation",
    value: 20.868181321456,
    municipalityLabel: "Municipality 12",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 12, Operator 4",
    municipality: "muni-12",
    operator: "op-4",
    canton: "canton-2",
    cantonLabel: "Canton 2",
  },
  {
    __typename: "OperatorObservation",
    value: 10.998923638031803,
    municipalityLabel: "Municipality 13",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 13, Operator 4",
    municipality: "muni-13",
    operator: "op-4",
    canton: "canton-3",
    cantonLabel: "Canton 3",
  },
  {
    __typename: "OperatorObservation",
    value: 18.575621909129744,
    municipalityLabel: "Municipality 14",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 14, Operator 4",
    municipality: "muni-14",
    operator: "op-4",
    canton: "canton-4",
    cantonLabel: "Canton 4",
  },
  {
    __typename: "OperatorObservation",
    value: 21.74633535629318,
    municipalityLabel: "Municipality 15",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 15, Operator 4",
    municipality: "muni-15",
    operator: "op-4",
    canton: "canton-5",
    cantonLabel: "Canton 5",
  },
  {
    __typename: "OperatorObservation",
    value: 19.10953393048299,
    municipalityLabel: "Municipality 16",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 16, Operator 4",
    municipality: "muni-16",
    operator: "op-4",
    canton: "canton-6",
    cantonLabel: "Canton 6",
  },
  {
    __typename: "OperatorObservation",
    value: 15.823542938960374,
    municipalityLabel: "Municipality 17",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 17, Operator 4",
    municipality: "muni-17",
    operator: "op-4",
    canton: "canton-7",
    cantonLabel: "Canton 7",
  },
  {
    __typename: "OperatorObservation",
    value: 16.37820959334821,
    municipalityLabel: "Municipality 18",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 18, Operator 4",
    municipality: "muni-18",
    operator: "op-4",
    canton: "canton-8",
    cantonLabel: "Canton 8",
  },
  {
    __typename: "OperatorObservation",
    value: 17.13313851684379,
    municipalityLabel: "Municipality 19",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 19, Operator 4",
    municipality: "muni-19",
    operator: "op-4",
    canton: "canton-9",
    cantonLabel: "Canton 9",
  },
  {
    __typename: "OperatorObservation",
    value: 12.73817205881581,
    municipalityLabel: "Municipality 20",
    operatorLabel: "Operator 4",
    muniOperator: "Municipality 20, Operator 4",
    municipality: "muni-20",
    operator: "op-4",
    canton: "canton-10",
    cantonLabel: "Canton 10",
  },
  {
    __typename: "OperatorObservation",
    value: 7.67037025219823,
    municipalityLabel: "Municipality 1",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 1, Operator 5",
    municipality: "muni-1",
    operator: "op-5",
    canton: "canton-1",
    cantonLabel: "Canton 1",
  },
  {
    __typename: "OperatorObservation",
    value: 20.980831413661438,
    municipalityLabel: "Municipality 2",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 2, Operator 5",
    municipality: "muni-2",
    operator: "op-5",
    canton: "canton-2",
    cantonLabel: "Canton 2",
  },
  {
    __typename: "OperatorObservation",
    value: 18.296424382295,
    municipalityLabel: "Municipality 3",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 3, Operator 5",
    municipality: "muni-3",
    operator: "op-5",
    canton: "canton-3",
    cantonLabel: "Canton 3",
  },
  {
    __typename: "OperatorObservation",
    value: 21.936535691790706,
    municipalityLabel: "Municipality 4",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 4, Operator 5",
    municipality: "muni-4",
    operator: "op-5",
    canton: "canton-4",
    cantonLabel: "Canton 4",
  },
  {
    __typename: "OperatorObservation",
    value: 25.99861183851477,
    municipalityLabel: "Municipality 5",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 5, Operator 5",
    municipality: "muni-5",
    operator: "op-5",
    canton: "canton-5",
    cantonLabel: "Canton 5",
  },
  {
    __typename: "OperatorObservation",
    value: 21.285344943721498,
    municipalityLabel: "Municipality 6",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 6, Operator 5",
    municipality: "muni-6",
    operator: "op-5",
    canton: "canton-6",
    cantonLabel: "Canton 6",
  },
  {
    __typename: "OperatorObservation",
    value: 21.318473102350122,
    municipalityLabel: "Municipality 7",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 7, Operator 5",
    municipality: "muni-7",
    operator: "op-5",
    canton: "canton-7",
    cantonLabel: "Canton 7",
  },
  {
    __typename: "OperatorObservation",
    value: 16.284992861976505,
    municipalityLabel: "Municipality 8",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 8, Operator 5",
    municipality: "muni-8",
    operator: "op-5",
    canton: "canton-8",
    cantonLabel: "Canton 8",
  },
  {
    __typename: "OperatorObservation",
    value: 25.429431578997942,
    municipalityLabel: "Municipality 9",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 9, Operator 5",
    municipality: "muni-9",
    operator: "op-5",
    canton: "canton-9",
    cantonLabel: "Canton 9",
  },
  {
    __typename: "OperatorObservation",
    value: 18.796717161846598,
    municipalityLabel: "Municipality 10",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 10, Operator 5",
    municipality: "muni-10",
    operator: "op-5",
    canton: "canton-10",
    cantonLabel: "Canton 10",
  },
  {
    __typename: "OperatorObservation",
    value: 21.041422487950904,
    municipalityLabel: "Municipality 11",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 11, Operator 5",
    municipality: "muni-11",
    operator: "op-5",
    canton: "canton-1",
    cantonLabel: "Canton 1",
  },
  {
    __typename: "OperatorObservation",
    value: 23.545332410795737,
    municipalityLabel: "Municipality 12",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 12, Operator 5",
    municipality: "muni-12",
    operator: "op-5",
    canton: "canton-2",
    cantonLabel: "Canton 2",
  },
  {
    __typename: "OperatorObservation",
    value: 18.62904273603577,
    municipalityLabel: "Municipality 13",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 13, Operator 5",
    municipality: "muni-13",
    operator: "op-5",
    canton: "canton-3",
    cantonLabel: "Canton 3",
  },
  {
    __typename: "OperatorObservation",
    value: 15.826105610674459,
    municipalityLabel: "Municipality 14",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 14, Operator 5",
    municipality: "muni-14",
    operator: "op-5",
    canton: "canton-4",
    cantonLabel: "Canton 4",
  },
  {
    __typename: "OperatorObservation",
    value: 17.366999671498675,
    municipalityLabel: "Municipality 15",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 15, Operator 5",
    municipality: "muni-15",
    operator: "op-5",
    canton: "canton-5",
    cantonLabel: "Canton 5",
  },
  {
    __typename: "OperatorObservation",
    value: 24.75092337286288,
    municipalityLabel: "Municipality 16",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 16, Operator 5",
    municipality: "muni-16",
    operator: "op-5",
    canton: "canton-6",
    cantonLabel: "Canton 6",
  },
  {
    __typename: "OperatorObservation",
    value: 23.85614972734726,
    municipalityLabel: "Municipality 17",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 17, Operator 5",
    municipality: "muni-17",
    operator: "op-5",
    canton: "canton-7",
    cantonLabel: "Canton 7",
  },
  {
    __typename: "OperatorObservation",
    value: 19.518623933007145,
    municipalityLabel: "Municipality 18",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 18, Operator 5",
    municipality: "muni-18",
    operator: "op-5",
    canton: "canton-8",
    cantonLabel: "Canton 8",
  },
  {
    __typename: "OperatorObservation",
    value: 21.20701902656768,
    municipalityLabel: "Municipality 19",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 19, Operator 5",
    municipality: "muni-19",
    operator: "op-5",
    canton: "canton-9",
    cantonLabel: "Canton 9",
  },
  {
    __typename: "OperatorObservation",
    value: 19.644620194375705,
    municipalityLabel: "Municipality 20",
    operatorLabel: "Operator 5",
    muniOperator: "Municipality 20, Operator 5",
    municipality: "muni-20",
    operator: "op-5",
    canton: "canton-10",
    cantonLabel: "Canton 10",
  },
];
