name: "Install yarn & node"
description: "Install dependencies and restores cache"
runs:
  using: "composite"
  steps:
    - name: Get installed Playwright version
      id: playwright-version
      shell: bash
      run: echo "PLAYWRIGHT_VERSION=1.31.2" >> $GITHUB_ENV

    - name: Cache playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

    - run: npx playwright install --with-deps chromium
      shell: bash
      if: steps.playwright-cache.outputs.cache-hit != 'true'

    - run: npx playwright install-deps
      shell: bash
      if: steps.playwright-cache.outputs.cache-hit != 'true'

    - run: npx playwright install
      shell: bash
