apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.screenshot.name }}-ingress
  labels: {{ include "elcom-strompreise.labels" . | nindent 4 }}
spec:
  rules:
  - http:
      paths:
      - path: /api/screenshot
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.screenshot.name }}
            port:
              name: {{ .Values.screenshot.port.name }}