apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name}}
  labels: {{ include "elcom-strompreise.labels" . | nindent 4 }}
spec:
  ports:
    - name: {{ .Values.web.port.name }}
      port: {{ .Values.web.port.number }}
      targetPort: {{ .Values.web.port.number }}
  selector:
    name: {{ .Values.web.name}}
