apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.web.name }}
  labels: {{ include "elcom-strompreise.labels" . | nindent 4 }}
    name: {{ .Values.web.name }}
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.web.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.web.name }}
    spec:
      containers:
        - image: {{ .Values.web.image }}
          name: {{ .Values.web.name }}
          imagePullPolicy: Never
          env:
            {{- range .Values.web.env.keys }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.web.env.secretKeyRef }}
                  key: {{ . }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.web.port.number }}
              protocol: TCP
              name: {{ .Values.web.port.name }}


