{{- if .Values.secrets.create }}
{{- if .Values.secrets.externalStore.paths.dockerConfigJSON }}
---
# ExternalSecret: Dockerconfig
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
  metadata:
  name: {{ include "elcom-strompreise.fullname" . }}
  labels:
    {{- include "elcom-strompreise.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "elcom-strompreise.fullname" . }}
    kind: SecretStore
    # Refresh: daily
    refreshInterval: 1440m0s
  target:
    name: {{ include "elcom-strompreise.fullname" . }}-{{ .Values.secrets.externalStore.paths.dockerConfigJSON.name }}
    creationPolicy: Owner
    template:
      engineVersion: v2

    type: kubernetes.io/dockerconfigjson
    data:
      .dockerconfigjson: '{{ `{{ .dockerconfig }}` }}'
      # For buildah task
      config.json: '{{ `{{ .dockerconfig }}` }}'
  data:
    - secretKey: dockerconfig
      remoteRef:
        key: {{ .Values.secrets.externalStore.paths.dockerConfigJSON.id }}
        property: dockerconfig
{{ end }}
{{ end }}