kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.traefik.name }}
  labels: {{ include "helm-charts.labels" . | nindent 4 }}
    name: {{ .Values.traefik.name }}
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.traefik.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ .Values.traefik.name }}
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: {{ .Values.traefik.name }}
          image: traefik:v3.1
          args:
            - --api.insecure
            - --providers.kubernetesingress
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
