apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.screenshot.name }}
  labels: {{ include "helm-charts.labels" . | nindent 4 }}
    name: {{ .Values.screenshot.name }}
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.screenshot.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.screenshot.name }}
    spec:
      containers:
        - name: {{ .Values.screenshot.name }}
          image: {{ .Values.screenshot.image }}
          imagePullPolicy: Never
          ports:
            - name: {{ .Values.screenshot.port.name }}
              containerPort: {{ .Values.screenshot.port.number }}


