name: Sync locales to Accent
on:
  push:
    branches: [main]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Install dependencies"
        uses: ./.github/workflows/install-deps

      - run: yarn run locales:extract
      - run: yarn run locales:sync
        env:
          ACCENT_API_KEY: ${{ secrets.ACCENT_API_KEY }}
      - run: git status
