name: GitLab Mirror

on: [push, delete]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: to_gitlab

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - name: Logging
        run: |
          git remote show origin
          git for-each-ref
      - name: Mirror to GitLab
        uses: wearerequired/git-mirror-action@c44c68aebe42de49a80a8dfd557416b6a0cafdad # v1.2.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:visualize-admin/electricity-prices-switzerland.git"
          destination-repo: "git@gitlab.ldbar.ch:interactivethings/elcom-electricity-price-website.git"
